attributes:
  node_name:
    value: 'zabbix'
    label: 'Node name'
    description: 'The name of the node where the plugin will be deployed'
    weight: 10
    type: "text"
    regex:
      source: '\S'
      error: "You must provide a name"
  username:
    value: "admin"
    label: "username"
    description: "Username for Zabbix Administrator"
    weight: 10
    type: "text"
  password:
    value: "zabbix"
    label: "password"
    description: "Password for Zabbix Administrator"
    weight: 20
    type: "password"
  db_password:
    value: "fae2oom_aeR6"
    label: "database password"
    description: "Password for Zabbix Database"
    weight: 30
    type: "password"
