attributes:
  on_external_node:
    value: true
    label: 'Install zabbix on external node'
    description: 'Zabbix server will be installed on the external node'
    weight: 1
    type: "checkbox"

  username:
    value: "admin"
    label: "username"
    description: "Username for Zabbix Administrator"
    weight: 15
    type: "text"
    regex:
      source: '\S'
      error: "You must provide a username"
  password:
    value: "zabbix"
    label: "password"
    description: "Password for Zabbix Administrator"
    weight: 20
    type: "password"
  db_password:
    value: "fae2oom_aeR6"
    label: "database password"
    description: "Password for Zabbix Database"
    weight: 30
    type: "password"
